/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fuensalida;

import com.fuensalida.BaseDatos.GestionAuditorioBD;
import com.fuensalida.BaseDatos.GestionEntradasBD;
import com.fuensalida.BaseDatos.GestionEstadosBD;
import com.fuensalida.BaseDatos.GestionFuncionesBD;
import com.fuensalida.beans.ButacaSesion;
import com.fuensalida.beans.EstadoBean;
import com.fuensalida.beans.SesionBean;
import com.fuensalida.utils.FechasUtils;
import com.fuensalida.utils.PrecioUtils;
import com.fuensalida.vista.VistaPantalla;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vPalomo
 */
public class VentaEntradasFrame extends javax.swing.JFrame {

    private ArrayList<ButacaSesion> butacasSel;
    private int numButacasSel;
    private int estadoButacasSel;
    private MiHasMap2 allButacas;
    private static final int totalButacas=466;
    private SesionBean sesionSelecionada;
    
    private PatioButacasPanel patioButacas;
    private VistaPantalla vistaP;
    private static final String icono="/com/fuensalida/images/CdCEdifIco.png";
    //private int idActividad=4;
    //private int idSesion=1;
    /**
     * Creates new form NewJFrame
     */
    public VentaEntradasFrame() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentaEntradasFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(VentaEntradasFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(VentaEntradasFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(VentaEntradasFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        sesionSelecionada=selecionaSesion();
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/com/fuensalida/images/CdCEdifIco.png")).getImage());
        
        patioButacas=new PatioButacasPanel();
        jPanel7.add(patioButacas);
        allButacas=patioButacas.getAllButacas();
        patioButacas.setSize(777, 434);
        
        inicializarButacas(sesionSelecionada, true);
        inicializarContadores(sesionSelecionada);
        cargarTablaSesiones();
        cargaAnos();
        selectMesActual();
        
        butacasSel=new ArrayList<ButacaSesion>();
        allButacas.getButacaJT(1).setSelected(false);
        
        /**
         * Abrimos la vista para clientes
         */
        if(vistaP==null){
            vistaP=new VistaPantalla(sesionSelecionada);
        }
        vistaP.setVisible(true);
        vistaP.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        
        jButton2.requestFocus();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        labelLibres = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        labelOcupadas = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        labelVentas = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        labelReservas = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        labelInvitaciones = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        labelAbonos = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        labelRecaudacion = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        labelSeleccionadas = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jAnos = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jMes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tActividades = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Depurar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deseleccionar todas las butacas");

        jLabel1.setForeground(new java.awt.Color(44, 102, 74));
        jLabel1.setText("Escenario");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Libres:");
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        labelLibres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelLibres.setForeground(new java.awt.Color(204, 0, 0));
        labelLibres.setText("12");
        labelLibres.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Ocupadas:");
        jLabel22.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        labelOcupadas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelOcupadas.setForeground(new java.awt.Color(204, 0, 0));
        labelOcupadas.setText("12");
        labelOcupadas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel31.setText("-----------------------------------");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Ventas:");
        jLabel28.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        labelVentas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelVentas.setForeground(new java.awt.Color(204, 0, 0));
        labelVentas.setText("12");
        labelVentas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Reservas:");
        jLabel32.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        labelReservas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelReservas.setForeground(new java.awt.Color(204, 0, 0));
        labelReservas.setText("12");
        labelReservas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Invitaciones:");
        jLabel34.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        labelInvitaciones.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelInvitaciones.setForeground(new java.awt.Color(204, 0, 0));
        labelInvitaciones.setText("12");
        labelInvitaciones.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Abonos:");
        jLabel36.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        labelAbonos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelAbonos.setForeground(new java.awt.Color(204, 0, 0));
        labelAbonos.setText("12");
        labelAbonos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Recauda.:");
        jLabel37.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        labelRecaudacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelRecaudacion.setForeground(new java.awt.Color(204, 0, 0));
        labelRecaudacion.setText("12");
        labelRecaudacion.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLayeredPane3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(labelLibres, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(labelOcupadas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(labelVentas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(labelReservas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(labelInvitaciones, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel36, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(labelAbonos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel37, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(labelRecaudacion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jLayeredPane3Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(labelLibres, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                        .addGroup(jLayeredPane3Layout.createSequentialGroup()
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(labelOcupadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelAbonos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(labelInvitaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelReservas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelVentas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelRecaudacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLibres))
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOcupadas))
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVentas))
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelReservas))
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInvitaciones))
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAbonos))
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRecaudacion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Seleccionadas:");
        jLabel38.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        labelSeleccionadas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelSeleccionadas.setForeground(new java.awt.Color(204, 0, 0));
        labelSeleccionadas.setText("0");
        labelSeleccionadas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSeleccionadas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(labelSeleccionadas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fuensalida/images/deseleccion3.png"))); // NOI18N
        jButton2.setToolTipText("Deseleccionar todas las butacas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel5.setBackground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jLabel24.setText("Libres");

        jPanel8.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jLabel25.setText("Vendidas");

        jPanel9.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jLabel26.setText("Reservadas");

        jLabel27.setText("Abonos");

        jPanel11.setBackground(new java.awt.Color(234, 137, 154));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jLabel29.setText("Invitaciones");

        jPanel12.setBackground(new java.awt.Color(59, 131, 189));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jLabel30.setText("No vender");

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel33.setText("Año:");

        jAnos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jAnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnosActionPerformed(evt);
            }
        });

        jLabel35.setText("Mes:");

        jMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMesActionPerformed(evt);
            }
        });
        jMes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jMesPropertyChange(evt);
            }
        });

        tActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Actividad", "Fecha", "Hora", "Compañía", "Precio", "idActividad", "idSesion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tActividades.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tActividades.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tActividades);
        if (tActividades.getColumnModel().getColumnCount() > 0) {
            tActividades.getColumnModel().getColumn(0).setMinWidth(100);
            tActividades.getColumnModel().getColumn(0).setPreferredWidth(200);
            tActividades.getColumnModel().getColumn(0).setMaxWidth(350);
            tActividades.getColumnModel().getColumn(5).setMinWidth(0);
            tActividades.getColumnModel().getColumn(5).setMaxWidth(0);
            tActividades.getColumnModel().getColumn(6).setMinWidth(0);
            tActividades.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel2.setText("v 0.2");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAnos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMes, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(131, 131, 131))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jAnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35)
                            .addComponent(jMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setAlignmentX(0.0F);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fuensalida/images/compra3.png"))); // NOI18N
        jButton4.setToolTipText("Vender");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fuensalida/images/reservas3.png"))); // NOI18N
        jButton5.setToolTipText("Reservar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fuensalida/images/Invitacion3.png"))); // NOI18N
        jButton6.setToolTipText("Invitación");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fuensalida/images/eliminar3.png"))); // NOI18N
        jButton7.setToolTipText("Pagar reserva");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jMenu2.setText("Archivo");

        jMenuItem3.setText("Pantalla Usuarios");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem2.setText("Generar Informe");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        Depurar.setText("Depurar");
        Depurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepurarActionPerformed(evt);
            }
        });
        jMenu2.add(Depurar);

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        deseleccionarTodo(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DepurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepurarActionPerformed
        debug();
    }//GEN-LAST:event_DepurarActionPerformed

    private void jAnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnosActionPerformed
        try {
            String ano=jAnos.getItemAt(jAnos.getSelectedIndex());
            String mes=FechasUtils.getNumMes(jMes.getItemAt(jMes.getSelectedIndex()));
            this.cargarTablaSesiones(ano, mes);
            
        } catch (Exception ex) {
            Logger.getLogger(VentaEntradasFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jAnosActionPerformed

    /**
     * Pantalla para la venta
     * @param evt 
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        venderTickets();
        
        vistaP.vaciaParpadeo();
        actualizaVistaUsuarios();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        reservarTickets();
        
        vistaP.vaciaParpadeo();
        actualizaVistaUsuarios();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        invitarTickets();
        
        vistaP.vaciaParpadeo();
        actualizaVistaUsuarios();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(estadoButacasSel==2){
            eliminarVenta();
            vistaP.removeAllParpadeo(1);
        }else if(estadoButacasSel==3 || estadoButacasSel==5){
            int respuesta=JOptionPane.showConfirmDialog(null, "Realmente quiere eliminar esta reserva o invitación","Aviso eliminación",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if(respuesta==0){ //respuesta: afirmativa=0, negativa=1
                GestionEntradasBD.eliminaReservaInvitacion(butacasSel, sesionSelecionada);
                vistaP.removeAllParpadeo(1);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Solo se pueden eliminar ventas, reservas e invitaciones");
            vistaP.removeAllParpadeo(2);
        }
        this.cambiarSesion(sesionSelecionada);
        deseleccionarTodo(false);
        
        actualizaVistaUsuarios();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JDialog frame = new JDialog(this, "Informe", true);
        frame.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
        frame.setIconImage(new ImageIcon(getClass().getResource(icono)).getImage());
        frame.getContentPane().add(new InformesPanel());
        frame.pack();
        frame.setVisible(true);
        //this.cambiarSesion(sesionSelecionada);
        frame.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if(vistaP==null){
            vistaP=new VistaPantalla(sesionSelecionada);
        }
        vistaP.setVisible(true);
        vistaP.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jMesPropertyChange
        
    }//GEN-LAST:event_jMesPropertyChange

    private void jMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMesActionPerformed
        try {
            String ano=jAnos.getItemAt(jAnos.getSelectedIndex());
            String mes=FechasUtils.getNumMes(jMes.getItemAt(jMes.getSelectedIndex()));
            this.cargarTablaSesiones(ano, mes);
            
        } catch (Exception ex) {
            Logger.getLogger(VentaEntradasFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMesActionPerformed

    private void actualizaVistaUsuarios(){
        //System.out.println("Actualizar 1");
        if(vistaP!=null){
            //System.out.println("Actualizar 2");
            vistaP.actualizar(sesionSelecionada);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaEntradasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaEntradasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Depurar;
    private javax.swing.JComboBox<String> jAnos;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JComboBox<String> jMes;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAbonos;
    private javax.swing.JLabel labelInvitaciones;
    private javax.swing.JLabel labelLibres;
    private javax.swing.JLabel labelOcupadas;
    private javax.swing.JLabel labelRecaudacion;
    private javax.swing.JLabel labelReservas;
    private javax.swing.JLabel labelSeleccionadas;
    private javax.swing.JLabel labelVentas;
    private javax.swing.JTable tActividades;
    // End of variables declaration//GEN-END:variables
   
    private JPanel botonera;
    
    /**
     * Busca en la base de datos las butacas de la sesion y las guarda en la
     * tabla de butacas y colorea los botones de cada una
     */
    private void coloreaButacas(SesionBean sesion) {
        ArrayList estadoButacas = GestionAuditorioBD.getEstadoButacas(sesion.getIdActividad(),sesion.getIdSesion());
        for (int i = 0; i < estadoButacas.size(); i++) {
            ButacaSesion b = (ButacaSesion) estadoButacas.get(i);
            allButacas.put(b);
            JToggleButton bJT = allButacas.getButacaJT(b.getIdButaca());
            if(b.getIdEstado()==3 || b.getIdEstado()==5 ){
                bJT.setToolTipText(GestionEntradasBD.getMotivo(b.getIdButaca(), sesion));
            }else{
                bJT.setToolTipText("");
            }
            ponColorButaca(b, bJT);
        }
        jPanel7.repaint();
    }

    /**
     * Colorea el jButton con respecto al estado de la butaca que se le pasa
     * @param b Butaca, se necesita para poder saber el estado de la misma
     * @param j Boton que se va a cambiar de color.
     */
    private void ponColorButaca(ButacaSesion b, JToggleButton j) {
        j.setForeground(Color.BLACK);
        EstadoBean estado= GestionEstadosBD.getEstado(b.getIdEstado());
        j.setBackground(
                new Color(
                        Integer.valueOf(estado.getColor().substring(0, 2), 16),
                        Integer.valueOf(estado.getColor().substring(2, 4), 16),
                        Integer.valueOf(estado.getColor().substring(4, 6), 16)));
        
    }

    /**
     * Inicialica los array de butacas necesarios para la aplicacion. También añade los manejadores, pero hay que
     * decirle si es la primera vez o no, ya que los manejadores solo se deben añadir una vez.
     * 
     * @param idActividad
     * @param idSesion
     * @param firstTime 
     */
    private void inicializarButacas(SesionBean sesion, boolean firstTime) {
        patioButacas.inicializarButacas();
        allButacas=patioButacas.getAllButacas();
        addAllListenerToButacas(firstTime);
        coloreaButacas(sesion);
    }

    /**
     * Deselecciona las butacas de la pantalla principal. Además si el parámetro es TRUE quita tambien los parpadeos de la vista
     * de cliente. El false se utilizará cuando se elimine una reserva, ya que será el eliminarReserva el que se encargará de
     * quitar el parpadeo y dejar el colo correcto.
     * @param eliminarParpadeo 
     */
    private void deseleccionarTodo(boolean eliminarParpadeo){
        Iterator it = allButacas.getButacaJT().entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry par = (Map.Entry) it.next();
            JToggleButton bJT = (JToggleButton) par.getValue();
            bJT.setSelected(false);
        }
        this.numButacasSel=0;
        this.labelSeleccionadas.setText("0");
        if(vistaP!=null && eliminarParpadeo)
            vistaP.removeAllParpadeo(estadoButacasSel);
        butacasSel=new ArrayList<ButacaSesion>();
        if(vistaP!=null)
            vistaP.reInitPatioButacas(sesionSelecionada);
    }
    /**
     * Añade la funcionalidad a las butacas, hace que se sumen, que se añadan al array de butacas sel, ...
     * @param firstTime Necesita saber si es la primera vez que se hace la carga, ya que los manejadores solo
     * se deben añadir una vez.
     */
    private void addAllListenerToButacas(boolean firstTime) {
        Iterator it = allButacas.getButacaJT().entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry par = (Map.Entry) it.next();
            int nBucata = (int) par.getKey();
            JToggleButton bJT = (JToggleButton) par.getValue();
            bJT.setBackground(new Color(0,255,0));
            if(firstTime){
                bJT.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        ButacaSesion b=allButacas.getButaca(nBucata);
                        if (bJT.isSelected()) {
                            if(numButacasSel!=0 && estadoButacasSel!=b.getIdEstado()){
                                JOptionPane.showMessageDialog(null, "No se pueden seleccionar butacas con estados difrentes");
                                bJT.setSelected(false);
                            }else{
                                estadoButacasSel=b.getIdEstado();
                                butacasSel.add(b);
                                patioButacas.setEtiquetaButacas(GestionAuditorioBD.getNumButaca(nBucata));
                                sumaButacaSel(true);
                                vistaP.addToParpadeo(nBucata);
                            }
                        } else {
                            butacasSel.remove(b);
                            sumaButacaSel(false);
                            vistaP.removeToParpadeo(nBucata, b.getIdEstado());
                        }
                        patioButacas.setNumEtiquetaButacas("" + nBucata);
                        //System.out.println("Indice: " + nBucata);
                    }
                });
            }
        }
    }

    private void sumaButacaSel(boolean estado) {
        if (estado) {
            numButacasSel++;
        } else {
            numButacasSel--;
        }
        labelSeleccionadas.setText("" + numButacasSel);
    }
    
    /**
     * Metodo para hacer pruebecillas
     */
    private void debug(){
        System.out.println("---------------------------------------------------------");
        System.out.println("Butacas sel: "+butacasSel.size());
        System.out.println("Array de butacas seleccionadas: "+butacasSel);
        
        System.out.println("numButacasSel: "+numButacasSel);
        System.out.println("estadoButacasSel: "+estadoButacasSel);
        
        System.out.println("Butacas: "+this.allButacas.sizeB());
        System.out.println("ButacasJT: "+this.allButacas.sizeBJT());
        System.out.println(this.allButacas);
        System.out.println("Sesion: "+sesionSelecionada);
        System.out.println("---------------------------------------------------------");
    }
    /**
     * Carga los contadores laretales de la aplicacion. Son los contadores relativos a la sesion y
     * actividad pasadas por parámtros
     * @param actividad id de la actividad que se quiere cargar
     * @param sesion id de la sesion que se quiere cargar.
     */
     private void inicializarContadores(SesionBean sesion) {
        if(sesion==null){
            labelLibres.setText("0");
            labelOcupadas.setText("0");
            labelVentas.setText("0");
            labelReservas.setText("0");
            labelInvitaciones.setText("0");
            labelAbonos.setText("0");
            labelRecaudacion.setText("0");
        }else{
            int ocupadas=GestionAuditorioBD.getOcupadas(sesion);
            int recaudacion=GestionEntradasBD.getRecaudacionSesion(sesion);
            labelLibres.setText(""+(totalButacas-ocupadas));
            labelOcupadas.setText(""+ocupadas);
            labelVentas.setText(""+GestionAuditorioBD.getButacasVendidas(sesion.getIdActividad(), sesion.getIdSesion()));
            labelReservas.setText(""+GestionAuditorioBD.getButacasReservadas(sesion.getIdActividad(), sesion.getIdSesion()));
            labelInvitaciones.setText(""+GestionAuditorioBD.getButacasInvitaciones(sesion.getIdActividad(), sesion.getIdSesion()));
            labelAbonos.setText(""+GestionAuditorioBD.getButacasAbonos(sesion.getIdActividad(), sesion.getIdSesion()));
            labelRecaudacion.setText(""+PrecioUtils.getPrecioEuros(recaudacion));
        }
        labelLibres.setHorizontalAlignment(SwingConstants.RIGHT);
        labelOcupadas.setHorizontalAlignment(SwingConstants.RIGHT);
        labelVentas.setHorizontalAlignment(SwingConstants.RIGHT);
        labelReservas.setHorizontalAlignment(SwingConstants.RIGHT);
        labelInvitaciones.setHorizontalAlignment(SwingConstants.RIGHT);
        labelAbonos.setHorizontalAlignment(SwingConstants.RIGHT);
        labelRecaudacion.setHorizontalAlignment(SwingConstants.RIGHT);
        
    }

     /**
      * Carga la tabla con las sesiones del mes actual.
      */
    private void cargarTablaSesiones() {
        String ano=FechasUtils.dameAnoFechaActual();
        String mes=FechasUtils.dameMesFechaActual();
        //System.out.println("fecha por defecto: "+mes+" "+ano);
        cargarTablaSesiones(ano, mes);
    }
    /**
     * Carga la tabla de sesiones con las del mes y año que se pasan por parámetro
     * @param ano Año de las sesiones que se quieren cargar
     * @param mes Mes de las sesiones que se quieren cargar
     */
    private void cargarTablaSesiones(String ano, String mes) {
        ArrayList<SesionBean> listaSesiones=GestionFuncionesBD.getSesiones(ano, mes);
        DefaultTableModel datosTabla=(DefaultTableModel) tActividades.getModel();
        for (int i = datosTabla.getRowCount(); i >0 ; i--) {
            datosTabla.removeRow(i-1);
            
        }
       
        for (int i=0;i<listaSesiones.size();i++){
            datosTabla.addRow(new String[]{
                listaSesiones.get(i).getDescripcion(),
                listaSesiones.get(i).getFecha(),
                listaSesiones.get(i).getHora(),
                listaSesiones.get(i).getCompania(),
                ""+PrecioUtils.getPrecioEuros(listaSesiones.get(i).getPrecio()),
                ""+listaSesiones.get(i).getIdActividad(),
                ""+listaSesiones.get(i).getIdSesion()
            });
        }     
        // Añadimos los listener a los botones de las butacas.
        if(!tieneListener){
            tActividades.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    ListSelectionModel lsm = (ListSelectionModel)e.getSource();
                    int indice=lsm.getMinSelectionIndex();
                    if(!e.getValueIsAdjusting() && indice!=-1){
                        String idActividad=(String) tActividades.getModel().getValueAt(indice, 5);
                        String idSesion= (String) tActividades.getModel().getValueAt(indice, 6);
                        sesionSelecionada=GestionFuncionesBD.getSesion(idActividad, idSesion);
                        cambiarSesion(sesionSelecionada);
                    }
                }
            });
            tieneListener=true;
        }
        if(tActividades.getModel().getRowCount()>0){
            tActividades.getSelectionModel().setSelectionInterval(0, 0);
            patioButacas.setVisible(true);
        }else{
            patioButacas.setVisible(false);
            sesionSelecionada=null;
            inicializarContadores(sesionSelecionada);
        }
        
    }
    
    private boolean tieneListener=false;
    
    public void cambiarSesion(SesionBean sesion){
        Long time=System.currentTimeMillis();
        deseleccionarTodo(true);
        inicializarButacas(sesion, false);
        inicializarContadores(sesion);
        Long time2=System.currentTimeMillis();
        System.out.println("Tiempo: "+(time2-time)+"ms");
    }
    /**
     * Carga los años en el combo de años. Se cargan todos los años existentes entre la mayor de las fechas y la menos de las fechas de las sesiones.
     */
    private void cargaAnos(){
        int mayor=Integer.parseInt(GestionFuncionesBD.getMaxMinAnoSesiones(true));
        int menor=Integer.parseInt(GestionFuncionesBD.getMaxMinAnoSesiones(false));
        String[] modelo = new String[(mayor-menor)+1];
        int indice=0;
        while(menor<=mayor){
            modelo[indice]=""+menor;
            menor++;
            indice++;
        }
        jAnos.setModel(new DefaultComboBoxModel<String>(modelo));
    }
    
    private void selectMesActual(){
        String mes=FechasUtils.dameMesFechaActual();
        jMes.setSelectedIndex(Integer.parseInt(mes)-1);
        tActividades.getSelectionModel().setSelectionInterval(0, 0);
    }

    private SesionBean selecionaSesion() {
        return GestionFuncionesBD.getSesionDefault();
    }

    private void venderTickets() {
        if(butacasSel.size()==0){
            JOptionPane.showMessageDialog(null, "No tiene selecionada ninguna butaca");
            return;
        }else if(estadoButacasSel!=1 && estadoButacasSel!=3){
            JOptionPane.showMessageDialog(null, "Solo se pueden vendes butacas libre o reservadas");
            deseleccionarTodo(true);
            return;
        }
        JDialog frame = new JDialog(this, "Venta de entradas", true);
        frame.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
        frame.setIconImage(new ImageIcon(getClass().getResource(icono)).getImage());
        frame.getContentPane().add(new VentaTicketPanel(butacasSel, sesionSelecionada));
        frame.pack();
        frame.setVisible(true);
        this.cambiarSesion(sesionSelecionada);
        frame.setVisible(false);
    }

    private void reservarTickets() {
        if(butacasSel.size()==0){
            JOptionPane.showMessageDialog(null, "No tiene selecionada ninguna butaca");
            return;
        }else if(estadoButacasSel!=1){
            JOptionPane.showMessageDialog(null, "Solo se pueden reservar butacas libre");
            deseleccionarTodo(true);
            return;
        }
        reservaInvitacionTickets(true);
    }

    private void invitarTickets() {
        if(butacasSel.size()==0){
            JOptionPane.showMessageDialog(null, "No tiene selecionada ninguna butaca");
            return;
        }else if(estadoButacasSel!=1){
            JOptionPane.showMessageDialog(null, "Solo se puede invitar en butacas libre");
            deseleccionarTodo(true);
            return;
        }
        reservaInvitacionTickets(false);
    }
    /**
     * 
     * @param isReserva Indica si es una reserva o una invitación. True es una reserva
     */
    private void reservaInvitacionTickets(boolean isReserva){
        String titulo=isReserva?"Reserva de entradas":"Invitaciones de entradas";
        JDialog frame = new JDialog(this, titulo, true);
        frame.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
        frame.setIconImage(new ImageIcon(getClass().getResource(icono)).getImage());
        frame.getContentPane().add(new ReservaTicketPanel(butacasSel, sesionSelecionada, isReserva));
        frame.pack();
        frame.setVisible(true);
        this.cambiarSesion(sesionSelecionada);
        frame.setVisible(false);
    }

    private void eliminarVenta() {
        String titulo="Eliminar venta";
        JDialog frame = new JDialog(this, titulo, true);
        frame.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
        frame.setIconImage(new ImageIcon(getClass().getResource(icono)).getImage());
        frame.getContentPane().add(new EliminarTicketPanel(butacasSel, sesionSelecionada));
        frame.pack();
        frame.setVisible(true);
        this.cambiarSesion(sesionSelecionada);
        frame.setVisible(false);
    }

    
}
